sidebar <- dashboardSidebar(disable = TRUE,
  sidebarMenu(
    id = "tabs",
    menuItem("Splash", tabName = "Splash", icon = icon("home")),
    menuItem("Home", tabName = "Home", icon = icon("home")),
    menuItem("AHU Trends", tabName = "AHU", icon = icon("wind")),
    menuItem("Chiller Plant Trends", tabName = "ChillerPlant", icon = icon("icicles")),
    menuItem("Boiler Plant Trends", tabName = "BoilerPlant", icon = icon("thermometer-full")),
    menuItem("Zone Trends", tabName = "Zone", icon = icon("coin")),
    menuItem("Perimeter Trends", tabName = "Perimeter", icon = icon("expand")),
    menuItem("Testing", tabName = "AHUmain", icon = icon("accusoft")),
    menuItem("Trend ONE", tabName = "trend1", icon = icon("accusoft")),
    menuItem('Trend Two', tabName = "trend2b", icon = icon("accusoft")),
    menuItem('Trend Three', tabName = 'trend3', icon = icon('accusoft')),
    menuItem('Trend 4', tabName = 'trend4c'),
    menuItem('Trend 4d', tabName = 'trend4d'),
    menuItem("Trend 5a ", tabName = 'trend5a'),
    menuItem("Trend 7 ", tabName = 'trend7'),
    menuItem("Trend 8a ", tabName = 'trend8a'),
    menuItem("Trend 8b ", tabName = 'trend8b'),
    menuItem("Trend 10", tabName = 'trend10'),
    menuItem("Trend 12", tabName = 'trend12'),
    menuItem('Trend 13a',tabName = 'trend13a',icon = icon('wind')),
    menuItem("Trend 14a", tabName = 'trend14a'),
    menuItem("Trend 15", tabName = 'trend15'),
    menuItem("Trend 17", tabName = 'trend17'),
    menuItem("Trend 18", tabName = 'trend18'),
    menuItem('Trend 19a', tabName = 'trend19a', icon = icon("expand")),
    menuItem('Trend 20a', tabName = 'trend20a', icon = icon("expand")),
    menuItem('Trend 21', tabName = 'trend21', icon = icon("expand")),
    menuItem('Trend 22', tabName = 'trend22', icon = icon("expand")),
    menuItem('Trend 23', tabName = 'trend23', icon = icon("expand")),
    menuItem('Trend 26', tabName = 'trend26', icon = icon("accusoft")),
    menuItem('Trend 27-37a', tabName = 'trend2737a', icon = icon("accusoft")),
    menuItem('Trend 27b',tabName = 'trend27b', icon = icon('queen')),
    menuItem('Trend 28b',tabName = 'trend28b', icon = icon('queen')),
    menuItem('Trend 29b',tabName = 'trend29b', icon = icon('queen')),
    menuItem('Trend 30b',tabName = 'trend30b', icon = icon('queen')),
    menuItem('Trend 31b',tabName = 'trend31b', icon = icon('queen')),
    menuItem('Trend 32b',tabName = 'trend32b', icon = icon('queen')),
    menuItem('Trend 33b',tabName = 'trend33b', icon = icon('queen')),
    menuItem('Trend 34b',tabName = 'trend34b', icon = icon('queen')),
    menuItem('Trend 36b',tabName = 'trend36b', icon = icon('queen')),
    menuItem('Trend 37b',tabName = 'trend37b', icon = icon('queen')),
    menuItem('Acrotab',tabName = 'AcroTab', icon = icon('queen'))
  )
)


#USE THE SIDEBAR MENU SO THAT YOU CAN FOLLOW WHAT HAPPENS IN THE BRT TOOL
#Link to it: https://www.cunybpl.org/nobas-brt-user-guide-v3/